"""
FABINTEL — Reports Page
Generate professional engineering reports from session analyses.
"""
import streamlit as st
import json
import io
from datetime import datetime
from components.ui_helpers import render_header, badge, empty_state, caution


def render():
    render_header()

    st.markdown("# Reports")

    wr = st.session_state.get('current_wafer_result')
    pr = st.session_state.get('current_process_result')

    if wr is None and pr is None:
        empty_state("📄", "NO ANALYSES AVAILABLE", "Perform a wafer inspection or process analysis to generate a report.")
        return

    st.markdown("## Generate Inspection Report")

    report_id = f"FI-{datetime.now().strftime('%Y%m%d-%H%M%S')}"
    report_time = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    if st.button("Generate Report", type="primary"):
        # ── Build Report ──────────────────────────────────
        report_md = f"""# FABINTEL INSPECTION REPORT

**Report ID:** {report_id}
**Generated:** {report_time}
**System:** FABINTEL Semiconductor Defect & Process Intelligence
**Environment:** Offline Analytics

---

## 1. Analysis Metadata

| Field | Value |
|-------|-------|
| Report ID | `{report_id}` |
| Date/Time | {report_time} |
| Operator | — |
| Session Analyses | {len(st.session_state.get('session_history', []))} |

"""

        report_json = {
            'report_id': report_id,
            'generated': report_time,
            'system': 'FABINTEL',
        }

        # ── Wafer Section ─────────────────────────────────
        if wr:
            result = wr['result']
            from inference.wafer_inference import get_model_info
            info = get_model_info()

            report_md += f"""---

## 2. Wafer Inspection

### Input
- **Source:** {wr.get('input_desc', '—')}
- **Original dimensions:** {wr['raw_img'].shape[0]} × {wr['raw_img'].shape[1]}
- **Processed dimensions:** 128 × 128

### Model
- **Architecture:** {info['name']}
- **Artifact:** `{info['artifact']}`
- **Loss:** {info['loss']}
- **Test Accuracy:** {info['test_accuracy']}
- **Test Macro F1:** {info['test_macro_f1']}

### Prediction
- **Defect class:** {result['class']}
- **Confidence:** {result['confidence']:.4f}

### Class Probabilities

| Class | Probability |
|-------|-------------|
"""
            for cls in sorted(result['probabilities'].keys(), key=lambda c: result['probabilities'][c], reverse=True):
                report_md += f"| {cls} | {result['probabilities'][cls]:.4f} |\n"

            report_md += f"""
### Defect Evidence
Grad-CAM spatial attention map generated for the predicted class.

"""
            report_json['wafer'] = {
                'input': wr.get('input_desc', '—'),
                'class': result['class'],
                'confidence': result['confidence'],
                'probabilities': result['probabilities'],
                'model': info['name'],
            }

        # ── Process Section ───────────────────────────────
        if pr:
            from inference.secom_inference import get_model_info as get_secom_info
            sinfo = get_secom_info()
            results = pr['results']

            report_md += f"""---

## 3. Process Analysis

### Model
- **Architecture:** {sinfo['name']}
- **Artifact:** `{sinfo['artifact']}`
- **Features:** {sinfo['input_features']}
- **Validation:** {sinfo['validation_strategy']}

### Predictions

| Record | Prediction | Failure Probability | Risk |
|--------|------------|---------------------|------|
"""
            for r in results:
                report_md += f"| {r['index']} | {r['prediction']} | {r['failure_probability']:.4f} | {r['risk']} |\n"

            report_json['process'] = {
                'model': sinfo['name'],
                'results': results,
            }

        # ── Limitations ───────────────────────────────────
        report_md += f"""
---

## 4. Engineering Interpretation

Model predictions represent statistical associations learned from historical data.
They do not establish physical root causes.

## 5. Limitations

- Grad-CAM indicates model-associated spatial attention, not physical causality.
- SHAP values indicate model-associated risk factors, not proven root causes.
- Wafer and process analyses are based on complementary datasets (WM-811K and SECOM)
  and are not directly linked at the individual wafer level.

## 6. Disclaimer

This report is generated by an automated analysis system for engineering review purposes.
All findings require independent verification by qualified process engineers before
corrective action is taken.

---
*FABINTEL — Semiconductor Defect & Process Intelligence Platform*
*Report ID: {report_id}*
"""

        # ── Display ───────────────────────────────────────
        st.markdown("### Report Preview")
        st.markdown(report_md)

        # ── Export ────────────────────────────────────────
        st.markdown("### Export")

        ec1, ec2, ec3 = st.columns(3)
        with ec1:
            st.download_button(
                "Export Markdown",
                data=report_md,
                file_name=f"{report_id}.md",
                mime="text/markdown",
            )
        with ec2:
            st.download_button(
                "Export JSON",
                data=json.dumps(report_json, indent=2, default=str),
                file_name=f"{report_id}.json",
                mime="application/json",
            )
        with ec3:
            # CSV export of session history
            history = st.session_state.get('session_history', [])
            if history:
                import pandas as pd
                csv_data = pd.DataFrame(history).to_csv(index=False)
                st.download_button(
                    "Export Session CSV",
                    data=csv_data,
                    file_name=f"{report_id}_session.csv",
                    mime="text/csv",
                )
